repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (staged only)
        entry: bash -c 'mypy --explicit-package-bases $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.py$")'
        language: system
        pass_filenames: false
