name: mecha_match
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - beautifulsoup4
  - fastapi
  - lxml
  - requests
  - uvicorn
  - pillow
  - psycopg2
  - sqlalchemy
  - black
  - mypy
  - pre-commit
  - pytest
  - ruff
