name: moduscrape
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - beautifulsoup4
  - fastapi
  - lxml
  - requests
  - uvicorn
  - pillow
  - psycopg2
  - black
  - mypy
  - pre-commit
  - pytest
  - ruff
  - scrapy
  - types-requests
  - tqdm
  - sqlalchemy
  - aiosqlite
  - alembic
  - pip:
      - scrapy-playwright
      - aiohttp
      - scrapy-user-agents
      - types-requests
      - -e .
      - -e ../shared
      - pytest-cov