name: mecha_match
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - beautifulsoup4
  - fastapi
  - lxml
  - requests
  - uvicorn
  - pillow
  - psycopg2
  - sqlalchemy
  - black
  - mypy
  - pre-commit
  - pytest
  - ruff
  - scrapy
  - types-requests
  - tqdm
  - pip:
      - scrapy-playwright
      - aiohttp
