name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: mecha_match
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.9

      - name: Run pre-commit hooks
        shell: bash -l {0}
        run: |
          conda activate mecha_match
          pre-commit run --all-files

      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          conda activate mecha_match
          pytest tests/ --maxfail=3 --disable-warnings --durations=10
