name: Conda CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: reverse-search
    - name: Lint
      run: ruff .
    - name: Format
      run: black --check .
    - name: Type Check
      run: mypy .
    - name: Test
      run: pytest
