name: Scraper CI

on:
  push:
    paths:
      - 'scraper/**'
  pull_request:
    paths:
      - 'scraper/**'
jobs:
  build-and-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: moduscrape
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.12

      - name: Run pre-commit hooks
        shell: bash -l {0}
        run: |
          conda activate moduscrape
          pre-commit run --all-files

      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          conda activate moduscrape
          pytest --maxfail=3 --disable-warnings --durations=10
